# Use root/example as user/password credentials
version: '3.1'

services:

  redis:
    image: "redis:alpine"

    # command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
     - "6379:6379"
    environment:
     - REDIS_REPLICATION_MODE=master

  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jingle

  posgre_db:
    image: postgres
    restart: always
    ports:
      - 3309:3307
    environment:
      POSTGRES_DB: wrb
      POSTGRES_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  rabbit:
     container_name: dev_rabbit
     hostname: rabbit
     image: rabbitmq:3.6.6-management
     environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=user
     ports:
        - "5672:5672"
        - "15672:15672"
